# =========================================================
# CONFIGURACIÓN GENERAL DE LA APLICACIÓN
# =========================================================
spring.application.name=RecetarioApp
server.port=8081

# =========================================================
# DATASOURCE - MySQL
# =========================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER:recetario}
spring.datasource.password=${DB_PASSWORD:recetario}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================================================
# JPA / HIBERNATE
# =========================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# =========================================================
# LOGGING
# =========================================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
